#Login
usericon=/html/body/div[1]/section/header/div/div/div[3]/div
workperxlogin=//*[@id="btn-workperx-login"]
phonenumber=//*[@id="userName"]
email=//*[@id="userName"]
proceed=//*[@id="root"]/div/div/div/section/div/div/div[2]
loginotpverification=//*[@id="initialField"]

#User KYC
completekyc=/html/body/div/div/div[6]/button[1]
userkycacknowledge=//*[@id="isConfirmConsent"]
userkyc-continue=/html/body/div/div/div[2]/div/div/section/div[7]/div/div/button
enteraadhaarnumber=//*[@id="kycDocumentNumber"]
aadhaarnumbercontinue=//*[@id="root"]/div/div[2]/div/div/div[2]/section/div[2]/div/div/button
aadhaarnumberotp=//*[@id="initialField"]
verifyaadhaarotp=//*[@id="root"]/div/div[2]/div/section/div[2]/div/div/button
verifyaadhaarnumber=//*[@id="confirmationDocumentNumber"]
verifyaadhaarname=//*[@id="confirmationName"]
verifyaadhaardob=//*[@id="confirmationDataOfBirth"]
verifyaadhaarfathername=//*[@id="confirmationFatherName"]
verifyaadhaaraddress=//*[@id="confirmationAddress"]
confirmaadhaar=/html/body/div/div/div[2]/div/section/div[6]/div/div/button
enterpannumber=//*[@id="kycDocumentNumber"]
pannumbercontinue=//*[@id="root"]/div/div[2]/div/div/div[2]/section/div[2]/div/div/button
userselfiecamera=//*[@id="root"]/div/div[2]/div/div/div[2]/section/div/div/div/div/label
uploadselfie=//*[@id="root"]/div/div[2]/div/div/div[2]/section/div/div/div/div[2]/div[2]/div/button
userkyc-complete-continue=//*[@id="root"]/div/div[2]/div/section/div[4]/div/div/button

#Company KYC
companykycacknowledge=//*[@id="isConfirmConsent"]
companykyc-continue=//*[@id="root"]/div/div[2]/div/div/section/div[6]/div/div/button
enterifmscode=//*[@id="kycDocumentNumber"]
ifmscontinue=//*[@id="root"]/div/div[2]/div/div/div[2]/section/div[2]/div/div/button
companyselfiecamera=//*[@id="root"]/div/div[2]/div/div/div[2]/section/div/div/div/div/label
uplaodifms=//*[@id="root"]/div/div[2]/div/div/div[2]/section/div/div/div/div[2]/div[2]/div/button
companykyc-complete-continue=//*[@id="root"]/div/div[2]/div/section/div[5]/div/div/button

#PhonpeApple
imagineapple= /html/body/div/div/div/div/div[4]/div/div/a/div/div[2]

#Workperx
workperxproceed=//*[@id="root"]/div/div/div[2]/div/section/div/div/div[2]/div/div/button
vouchers=/html/body/div/div[3]/div/div/div[6]/div/div[1]/a/div/div
workperxecommerceviewall=//*[@id="giftCards"]/div[1]/div/div[2]/a
workperxflipkartgc=//*[@id="giftCards"]/div/div/div/div[1]/div/a/table/tbody/tr/td[2]
lta=/html/body/div/div[3]/div/div/div[6]/div/div[2]/a/div/div
meal=/html/body/div/div[3]/div/div/div[6]/div/div[3]/a/div/div
travel=/html/body/div/div[3]/div/div/div[6]/div/div[4]/a/div/div
workperxtravelcleartrip=/html/body/div/div[2]/div/div[4]/div/div[1]/a/div/div[2]
workperxppc=//*[@id="allBlocks"]/div[5]/div/div/div/div[1]/div/div/a/table/tbody/tr/td[2]
workperxvirtualyesbankppc=//*[@id="giftCards"]/div/div/div/div[1]/div/a/table/tbody/tr/td[2]/div[1]
workperxvehicles=//*[@id="allBlocks"]/div[7]/div/div/div/div[1]/div/div/a/table/tbody/tr/td[2]/div[2]
workperxdeals=/html/body/div/div[3]/div/div/div[13]/div/div/a/div/div

#Send a Digital Certificate
sendadigitalcertificate=//*[@id="allBlocks"]/div[11]/div/div/div/div[1]/a/div/div/h4
selectaward=//*[@id="edit-award-type"]
recepientname=//*[@id="edit-recipient-name"]
recepientemail=//*[@id="edit-recipient-email"]
selecttemplate=//*[@id="employee-award-send-award"]/div[3]/div[3]/div[2]/div/div/div/div/div[1]/div/label/img
awardheading=//*[@id="edit-award-heading"]
awardbody=//*[@id="edit-award-body"]
preview=//*[@id="edit-next"]
send=//*[@id="send-button"]

#Send as a Gift
Sendasagift=//*[@id="cardDetails"]/section[3]/form/label/input
Sendgcfirstname=//*[@id="cardDetails"]/section[3]/form/div[3]/div[1]/div[1]/div/input
Sendgclastname=//*[@id="cardDetails"]/section[3]/form/div[3]/div[1]/div[2]/div/input
Sendgcemail=//*[@id="cardDetails"]/section[3]/form/div[3]/div[2]/div[1]/div/input
Sendphonenumber=//*[@id="cardDetails"]/section[3]/form/div[3]/div[2]/div[2]/div/input
Sendtheme=/html/body/app-root/div/app-card-details/div/div/section[3]/form/div[3]/div[3]/div/owl-carousel-o/div/div[1]/owl-stage/div/div/div[1]/div/aside/img
Sendmessage=//*[@id="cardDetails"]/section[3]/form/div[3]/div[4]/textarea
workperxnb=//*[@id="root"]/div/center/div/div/div[3]/div[4]/div[9]/div[1]/div[1]/p/div/table/tr/td[2]/table/tr/td/div[1]/span
dealsnb=//*[@id="root"]/div/center/div/div/div[3]/div[4]/div[4]/div[1]/div[1]/p/div/table/tr/td[2]/table/tr/td/div[1]/span

#Workperx Admin
Admin=//*[@id="accordionExample"]/div[6]/h2/button/span

#Redeem Gift Cards
gcmviewall=//*[@id="isVoucherListViewAllDiv"]
ecommerceviewall=//*[@id="giftCards"]/div[1]/div/div[2]/a
flipkartgc=//*[@id="giftCards"]/div/div/div/div[1]/div/a/table/tbody/tr/td[2]
apollogc=/html/body/div[1]/div[5]/div/div[8]/div/div/div/div[1]/div[2]/div/a/table/tbody/tr/td[2]/div[1]
2nd-denomination=//*[@id="priceTable"]/div/table/tbody/tr[2]/td[3]/a[2]
3rd-denomination=//*[@id="priceTable"]/div/table/tbody/tr[3]/td[3]/a[2]
gc-termofuse=/html/body/app-root/div/app-card-details/div/div/section[3]/div[1]/label/input
buygiftcard=//*[@id="payButton"]

#Redeem Prepaid Cards
ppcviewall=//*[@id="allBlocks"]/div[11]/div/div/a/div/div[2]
virtualyesbankppc=//*[@id="giftCards"]/div/div/div/div[1]/div/a/table/tbody/tr/td[2]
enterdynamicvalue=//*[@id="priceTable"]/div/table/tbody/tr[4]/td[1]/input
add-dynamic-denomination=//*[@id="priceTable"]/div/table/tbody/tr[4]/td[3]/a[2]
gcmcontinue = //*[@id="payButton"]
ppc-termofuse=//*[@id="cardDetails"]/section[3]/div[1]/label/input
buyppc=//*[@id="payButton"]

#Redeem Vehicles
vehicleviewall=//*[@id="allBlocks"]/div[14]/div/div/a/div/div[2]/h5
enteraddressline1=//*[@id="cardDetails"]/section[3]/form/div[3]/div[1]/div/input
enteraddressline2=//*[@id="cardDetails"]/section[3]/form/div[3]/div[2]/div/input
entercity=//*[@id="cardDetails"]/section[3]/form/div[4]/div[1]/div/input
enterstate=//*[@id="cardDetails"]/section[3]/form/div[4]/div[2]/div/input
enterzipcode=//*[@id="cardDetails"]/section[3]/form/div[5]/div[1]/div/input
entercountry=//*[@id="cardDetails"]/section[3]/form/div[5]/div[2]/div/input
vehicle-termofuse=//*[@id="cardDetails"]/section[3]/div[1]/label/input
buyvehicle=//*[@id="payButton"]

#Wallet Payment
walletpay=//*[@id="panel1a-content"]/p/div/div/div[1]/table/tr/td/div/table/tr[1]/td[2]/button
walletredeemotp=//*[@id="otp"]
lowbalancepopupok=/html/body/div[1]/div/center/div/div/div[3]/div[4]/div[1]/div[2]/div/div/div/p/div/div/div[3]/div[2]/div[2]/div/button[1]
walletconfirmotp=//*[@id="panel1a-content"]/p/div/div/div[1]/table/tr/td/div/table/tr[3]/td[2]/button
vieworder=/html/body/app-root/div/app-payment-success/div/div[2]/div/div[3]/a
viewgcdetails=/html/body/div/div/div[2]/div/div/section/div/div[2]/div/div/div/div/div/div[1]/div/table/tbody/tr/td[4]/div/table/tbody/tr/td[1]/strong

#UPI Payment
upipayment=//*[@id="root"]/div/center/div/div/div[3]/div[4]/div[3]/div[1]/div[1]/p/div/table/tr/td[2]/table/tr/td/div[1]/span
enterupi=//*[@id="vpa"]
verifyupi=//*[@id="panel1a-content"]/p/div/div/table/tr/td/div/table/tr[2]/td[2]/button
payupi=//*[@id="panel1a-content"]/p/div/div/table/tr/td/div/table/tr[2]/td[2]/button

#UPI intent Apps
upi-intentapp=//*[@id="root"]/div/center/div/div/div[3]/div[4]/div[4]/div[1]/div[1]/p/div/table/tr/td[2]/table/tr/td/div[1]/span
selectphonepe=//*[@id="panel1a-content"]/p/div/table/tr[1]/td[2]/img
upi-intentpay=//*[@id="panel1a-content"]/p/div/table/tr[6]/td/button
noappfound=//*[@id="otp-modal"]/div[2]/div[2]/div/button

#Netbanking Payment
nbpayment=//*[@id="root"]/div/center/div/div/div[3]/div[4]/div[6]/div[1]/div[1]/p/div/table/tr/td[2]/table/tr/td/div[1]/span
clickbanklist=//*[@id="panel1a-content"]/p/div/div/table/tr/td/div/table/tr[2]/td[1]/div/div/div[1]/div/input
selectbank=//*[@id="panel1a-content"]/p/div/div/table/tr/td/div/table/tr[2]/td[1]/div/div/div[2]/ul/li
nbpay=//*[@id="panel1a-content"]/p/div/div/table/tr/td/div/table/tr[2]/td[2]/div/button
nbusername=//*[@id="username"]
nbpwd=//*[@id="password"]
nblogin=//*[@id="btnSubmit"]
nbconfirm=/html/body/div/div/div/div[2]/div/div/form/input[2]

#Card Payment
cardpayment=//*[@id="root"]/div/center/div/div/div[3]/div[4]/div[6]/div[1]/div[1]/p/div/table/tr/td[2]/table/tr/td/div[1]/span
cardnumber=//*[@id="cardNumber"]
expirydate=//*[@id="expiryDate"]
cvv=//*[@id="cvv"]
nameoncard=//*[@id="cardHolderName"]
cardpay=//*[@id="panel2a-content"]/p/div/div/table/tr/td/div/table/tr[5]/td[2]/button

#Others
home=/html/body/div/div/div[3]/div/footer/div[2]/a/img
myaccount=/html/body/div/div/div[3]/div/footer/div[3]/a/img
pendingorders=//*[@id="root"]/div/div[2]/div/div/section/div/div[2]/div/div/section/ul/li[2]/span
logout=//*[@id="accordionExample"]/div[7]/div/h2/button
logoutyes=//*[@id="root"]/div/div[2]/div/section/div/div[1]/section[2]/div/div/div/div[2]/section/div/div[1]/div/button


#PulseHRM
username=//*[@id="P515_USERNAME"]
password=//*[@id="P515_PASSWORD"]
signin=//*[@id="B327065516080458935"]
punchin=//*[@id="P1_PUNCH_IN"]
punchout=//*[@id="P1_PUNCH_OUT"]