version: '3.8'

services:
 aut-lifafaend2end:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-maven-project
    environment:
      - DISPLAY=:99
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: sh -c "Xvfb :99 -ac & mvn test"