version: '3.8'

services:
  automation-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-maven-project:latest
    environment:
      - DISPLAY=:99
      - IS_DOCKER=true
    volumes:
      - .:/app
    entrypoint: ["/app/entrypoint.sh"]