version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: my-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  maven_project:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-maven-project
    environment:
      - DISPLAY=:99
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: sh -c "Xvfb :99 -ac & mvn test"

volumes:
  jenkins_home:
